'use client'

import React from 'react'
import { ShieldAlert, CheckCircle2, FileText, BarChart3 } from 'lucide-react'
import { SectionHeading } from '@/components/brand/SectionHeading'
import { GlassCard } from '@/components/brand/GlassCard'

export function BentoDifferentiators() {
  return (
    <section className="py-24 relative overflow-hidden">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 relative z-10">
        <SectionHeading
          eyebrow="Differentiators"
          title="Engineered for precision and transparent risk."
          subtitle="Three core principles separate YieldCompass from traditional APY aggregators and black-box yield optimizers."
          align="center"
          className="mb-14"
        />

        {/* Bento Grid: 1 Large Featured Card + 2 Medium Cards */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Card 1: Risk-Gated by Design (Featured, Large - 7 cols) */}
          <GlassCard
            featured
            className="lg:col-span-7 p-7 md:p-9 flex flex-col justify-between"
          >
            <div>
              <div className="flex items-center justify-between mb-4">
                <span className="badge badge-indigo text-xs">Core Innovation</span>
                <span className="flex items-center gap-1.5 text-xs text-[var(--positive)] font-semibold">
                  <CheckCircle2 size={13} /> Active Verification
                </span>
              </div>

              <h3 className="text-xl md:text-2xl font-bold text-[var(--text)] mb-3">
                Risk-Gated by Design
              </h3>
              <p className="text-sm text-[var(--text-secondary)] leading-relaxed mb-6">
                Vault capital is never deployed blindly. If an underlying pool suffers an exploit, oracle staleness, or falls below the series risk threshold, the smart contract gate immediately blocks deposits and freezes deployments.
              </p>

              {/* Visual Gate Mock Inside Bento */}
              <div className="p-4 rounded-xl bg-[var(--surface-strong)] border border-[rgba(52,211,153,0.3)] space-y-3">
                <div className="flex items-center justify-between text-xs pb-2 border-b border-[var(--border)]">
                  <span className="font-semibold text-[var(--text)]">Solana Gate Evaluation</span>
                  <span className="badge badge-green text-[10px]">Gate Passed</span>
                </div>
                <div className="grid grid-cols-2 gap-3 text-xs">
                  <div className="p-2.5 rounded-lg bg-[var(--surface)] border border-[var(--border)]">
                    <span className="text-[10px] text-[var(--text-muted)] block uppercase font-medium">Protocol Score</span>
                    <span className="text-sm font-bold text-[var(--accent)] tabular">88 &ge; 75 required</span>
                  </div>
                  <div className="p-2.5 rounded-lg bg-[var(--surface)] border border-[var(--border)]">
                    <span className="text-[10px] text-[var(--text-muted)] block uppercase font-medium">Telemetry Age</span>
                    <span className="text-sm font-bold text-[var(--positive)] tabular">12m &le; 60m max</span>
                  </div>
                </div>
              </div>
            </div>

            <div className="mt-6 pt-4 border-t border-[var(--border)] flex items-center gap-2 text-xs text-[var(--text-muted)]">
              <ShieldAlert size={14} className="text-[var(--accent)]" />
              <span>Protects tranche capital against sudden protocol degradation</span>
            </div>
          </GlassCard>

          {/* Column with 2 Stacked Cards (5 cols) */}
          <div className="lg:col-span-5 flex flex-col gap-6">
            {/* Card 2: Realized-Yield Truth */}
            <GlassCard className="p-6 sm:p-7 flex-1 flex flex-col justify-between">
              <div>
                <div className="w-9 h-9 rounded-xl bg-[var(--accent-soft)] border border-[rgba(52,211,153,0.3)] text-[var(--accent)] flex items-center justify-center mb-3.5">
                  <BarChart3 size={18} />
                </div>
                <h3 className="text-lg font-bold text-[var(--text)] mb-2">
                  Realized-Yield Truth
                </h3>
                <p className="text-xs sm:text-sm text-[var(--text-secondary)] leading-relaxed mb-4">
                  We discount speculative governance tokens and measure genuine stablecoin cashflow generated by real borrowers and economic activity over 7 and 30 day windows.
                </p>
              </div>
              <div className="pt-3 border-t border-[var(--border)] text-xs text-[var(--text-muted)] flex items-center justify-between">
                <span>Metrics: 7d & 30d Realized</span>
                <span className="text-[var(--accent)] font-semibold">Zero Speculation</span>
              </div>
            </GlassCard>

            {/* Card 3: Explainable */}
            <GlassCard className="p-6 sm:p-7 flex-1 flex flex-col justify-between">
              <div>
                <div className="w-9 h-9 rounded-xl bg-[var(--accent-soft)] border border-[rgba(52,211,153,0.3)] text-[var(--accent)] flex items-center justify-center mb-3.5">
                  <FileText size={18} />
                </div>
                <h3 className="text-lg font-bold text-[var(--text)] mb-2">
                  Explainable with Cited Facts
                </h3>
                <p className="text-xs sm:text-sm text-[var(--text-secondary)] leading-relaxed mb-4">
                  Deterministic mathematical rules compute the 0-100 score. AI models never invent or hallucinate metrics; they only extract cited factual statements from public security audits.
                </p>
              </div>
              <div className="pt-3 border-t border-[var(--border)] text-xs text-[var(--text-muted)] flex items-center justify-between">
                <span>Cited Reports: OtterSec, Neodyme, Sec3</span>
                <span className="text-[var(--positive)] font-semibold">100% Verifiable</span>
              </div>
            </GlassCard>
          </div>
        </div>
      </div>
    </section>
  )
}
